import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { neobrutalism, shadesOfPurple } from "@clerk/themes";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        theme: [shadesOfPurple, neobrutalism],
      }}
    >
      <html lang="en">
        <body>
          <Header />
          <main>{children}</main>
          <Toaster richColors />
        </body>
      </html>
    </ClerkProvider>
  );
}
